# BACKGROUND
background {
    # path = ~/.config/hypr/Ultrakill.png 
    color = rgba(0, 0, 0, 0) 
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = true
    immediate_render = true 
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 1)
    font_size = 22
    font_family = VCR OSD Mono
    position = 133, 48
    halign = left
    valign = center
}

# TIME
label {
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(255, 255, 255, 1)
    font_size = 100
    font_family = VCR OSD Mono
    position = 128, 136
    halign = left
    valign = center
}

# MESSAGE
label {
    text = Welcome back, RAMN
    color = rgba(255, 255, 255, 1)
    font_size = 30
    font_family = VCR OSD Mono
    position = 133, -30
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    size = 630, 90
    rounding = 0
    outline_thickness = 4
    dots_size = 0.05 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    outer_color = rgba(255, 255, 255, 1)
    inner_color = rgba(10, 10, 10, 1)
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    font_family = VCR OSD Mono
    placeholder_text = <i><span foreground="##ffffff99"></span></i>
    hide_input = false
    position = 136, -114
    halign = left
    valign = center
}