 
 
general {
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}
 
listener {
    timeout = 240
    on-timeout = brightnessctl -s ; brightnessctl set 40% ; notify-send -i ~/.config/dunst/icons/death.png "El sistema se apagara pronto"
    on-resume = brightnessctl -r
}
 
listener {
    timeout = 300
    on-timeout = brightnessctl -s; brightnessctl -d msiacpi::kbd_backlight s 0 && hyprctl dispatch dpms off && mpvpaper -l overlay -vs -o 'no-audio loop' '*' ~/.config/hypr/ultrakill.mp4 -f & sleep 0.65; hyprlock; pkill mpvpaper 
    on-resume = brightnessctl -d msiacpi::kbd_backlight s 1; mpvpaper -l overlay -vs -o 'no-audio loop' '*' ~/.config/hypr/ultrakill.mp4 -f & sleep 0.65; hyprctl dispatch dpms on; brightnessctl -r
}
